# # @format

# name: puthagam
# version: 2.1.41+81
# publish_to: none
# description: A new Flutter project.
# environment:
#   sdk: ">=2.16.1 <3.0.0"


# dependencies:
#   flutter:
#     sdk: flutter
#   cupertino_icons: ^1.0.2
#   hexcolor: ^3.0.1
#   icons_launcher: ^3.0.0
#   dotted_border: ^2.0.0+3
#   intl: ^0.20.2
#   square_percent_indicater: ^0.1.0
#   in_app_purchase_storekit: ^0.3.0
#   just_audio: ^0.9.28
#   flutter_switch: ^0.3.2
#   flutter_rating_bar: ^4.0.1
#   image_picker: ^1.1.2
#   pin_code_fields: ^8.0.1
#   carousel_slider: ^5.0.0
#   google_fonts: ^4.0.4
#   shared_preferences: ^2.0.15
#   get_storage: ^2.0.3
#   animated_theme_switcher: ^2.0.1
#   webviewx: ^0.2.1
#   path_provider: ^2.1.3     #2.0.11
#   shimmer: ^3.0.0
#   provider: ^6.0.5
#   get: ^4.6.5
#   http: ^0.13.4
#   connectivity: ^3.0.6
#   fluttertoast: ^8.0.9
#   firebase_dynamic_links: ^6.1.4
#   share_plus: ^6.3.4
#   # downloads_path_provider_28: ^0.1.2
#   dio: ^5.8.0+1
#   audio_service: ^0.18.9
#   amplify_flutter: ^1.0.0
#   amplify_auth_cognito: ^1.0.1
#   velocity_x: ^4.3.1
#   wakelock: ^0.6.2
#   launch_review: ^3.0.1
#   flutter_html: ^3.0.0-beta.2
#   url_launcher: ^6.1.10
#   google_sign_in: ^6.2.2
#   flutter_facebook_auth: ^6.0.4
#   cached_network_image: ^3.2.3
#   just_audio_background: ^0.0.1-beta.7
#   firebase_messaging: ^15.2.4
#   flutter_local_notifications: ^18.0.1
#   record: ^5.2.1
#   audioplayers: ^6.2.0
#   flutter_fadein: ^2.0.0
#   retrofit: ^4.4.2
#   audio_waveforms: ^1.0.4
#   lottie: ^3.0.0
#   flutter_document_picker: ^5.1.0
#   amplify_analytics_pinpoint: ^1.0.1
#   flutter_audio_streaming:
#     git:
#       url: https://github.com/himanshukharemipl/flutter_audio_streaming
#       ref: master
#   getwidget: ^6.0.0
#   flutter_launcher_icons: ^0.13.1      #0.11.0
#   video_player: ^2.4.10
#   swipe_to: ^1.0.2
#   image_cropper: ^4.0.1
#   keep_screen_on: ^4.0.0
#   percent_indicator: ^4.2.2
#   readmore: ^3.0.0
#   sign_in_with_apple: ^6.1.4
#   crypto: ^3.0.3
#   flutter_secure_storage: ^8.0.0
#   in_app_purchase: ^3.1.5
#   firebase_remote_config: ^5.4.2
#   new_version_plus: ^0.0.9
#   pinch_zoom: ^2.0.0
#   flutter_svg: ^2.0.5
#   country_pickers: ^3.0.1
#   upi_india: ^3.0.1
#   extended_image: ^8.0.3
#   phonepe_payment_sdk: ^3.0.0
#   permission_handler: ^11.0.1
#   flutter_stripe: ^11.4.0
#   geolocator: ^12.0.0
#   flutter_dotenv: ^5.0.2
#   cloud_firestore: ^5.6.5
#   firebase_core: ^3.12.1
#   aws_common: ^0.4.2+5
#   amplify_secure_storage: ^0.3.0+4



# flutter_icons:
#   android: "ic_launcher"
#   ios: true
#   adaptive_icon_background: "assets/images/logo.png"


#   remove_alpha_ios: true
#   image_path: "assets/images/logo.png"
#   min_sdk_android: 21 # android min sdk min:16, default 21
#   web:
#     generate: true
#     image_path: "assets/images/logo.png"
#     background_color: "#hexcode"
#     theme_color: "#hexcode"

# dependency_overrides:
#   firebase_core_platform_interface: 4.5.1


# dev_dependencies:
#   retrofit_generator: ^9.1.9
#   build_runner: any
#   flutter_lints: ^5.0.0
#   flutter_test:
#     sdk: flutter

# flutter:
#   # The following line ensures that the Material Icons font is
#   # included with your application, so that you can use the icons in
#   # the material Icons class.
#   uses-material-design: true

#   assets:
#     - assets/splash/
#     - assets/icons/
#     - assets/images/
#     - assets/fonts/
#     - assets/lottie/
#     - assets/.env
#   fonts:
#     - family: SF-Pro-Display
#       fonts:
#         - asset: assets/fonts/SF-Pro-Display-Semibold.otf
#         - asset: assets/fonts/SF-Pro-Display-Medium.otf
#         - asset: assets/fonts/SF-Pro-Display-Regular.otf

name: puthagam
version: 2.1.41+81
publish_to: none
description: A new Flutter project.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  hexcolor: ^3.0.1
  icons_launcher: ^3.0.1
  dotted_border: ^2.1.0
  intl: ^0.20.2
  square_percent_indicater: ^0.1.0
  in_app_purchase_storekit: ^0.3.8
  just_audio: ^0.9.36
  flutter_switch: ^0.3.2
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.1.2
  pin_code_fields: ^8.0.1
  carousel_slider: ^5.0.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.2
  get_storage: ^2.1.1
  animated_theme_switcher: ^2.0.2
  webviewx: ^0.2.2
  path_provider: ^2.1.3
  shimmer: ^3.0.0
  provider: ^6.1.2
  get: ^4.6.6
  http: ^0.13.3
  connectivity_plus: ^6.1.3
  fluttertoast: ^8.2.4
  firebase_dynamic_links: ^6.1.4
  share_plus: ^10.1.4
  dio: ^5.4.1
  audio_service: ^0.18.13
  amplify_flutter: ^2.6.0
  amplify_auth_cognito: ^2.6.0
  velocity_x: ^4.3.1
  wakelock_plus: ^1.1.0
  launch_review: ^3.0.1
  flutter_html: ^3.0.0-beta.2
  url_launcher: ^6.2.5
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.1
  cached_network_image: ^3.3.1
  just_audio_background: ^0.0.1-beta.10
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^18.0.1
  record: ^5.2.1
  audioplayers: ^6.2.0
  flutter_fadein: ^2.0.0
  retrofit: ^4.4.2
  audio_waveforms: ^1.0.4
  lottie: ^3.1.0
  flutter_document_picker: ^5.2.0
  amplify_analytics_pinpoint: ^2.6.0
  flutter_audio_streaming:
    git:
      url: https://github.com/himanshukharemipl/flutter_audio_streaming
      ref: master
  getwidget: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  video_player: ^2.8.1
  swipe_to: ^1.0.2
  image_cropper: ^9.0.0
  keep_screen_on: ^4.0.0
  percent_indicator: ^4.2.3
  readmore: ^3.0.0
  sign_in_with_apple: ^6.1.0
  crypto: ^3.0.3
  flutter_secure_storage: ^9.2.1
  in_app_purchase: ^3.2.1
  firebase_remote_config: ^5.4.2
  new_version_plus: ^0.1.0
  pinch_zoom: ^2.0.0
  flutter_svg: ^2.0.10
  country_pickers: ^3.0.1
  upi_india: ^3.0.1
  extended_image: ^10.0.0
  phonepe_payment_sdk: ^3.0.0
  permission_handler: ^11.3.0
  flutter_stripe: ^11.4.0
  geolocator: ^12.0.0
  flutter_dotenv: ^5.1.0
  cloud_firestore: ^5.6.5
  firebase_core: ^3.12.1
  aws_common: ^0.7.5
  amplify_secure_storage: ^0.5.3
  

dependency_overrides:
  firebase_core_platform_interface: ^4.5.1
  http: ^1.0.0
  web: ^1.0.0

dev_dependencies:
  retrofit_generator: ^9.1.9
  build_runner: any
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/splash/
    - assets/icons/
    - assets/images/
    - assets/fonts/
    - assets/lottie/
    - assets/.env

  fonts:
    - family: SF-Pro-Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
        - asset: assets/fonts/SF-Pro-Display-Regular.otf

flutter_icons:
  android: true
  ios: true
  adaptive_icon_background: "assets/images/logo.png"
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#FFFFFF"
    theme_color: "#000000"
